name: json_conditional
description: A library to create conditional evaluators from JSON or JSON-like structures.
homepage: https://github.com/peiffer-innovations/json_conditional

version: 2.1.0+3

environment:
  sdk: '>=2.17.0 <3.0.0'

analyzer:
  exclude: [lib/generated/**]

dependencies:
  json_class: ^2.1.2+4
  meta: ^1.7.0

dev_dependencies:
  test: ^1.21.1

ignore_updates:
  # Ignoring everything in flutter_test as those are all point-in-time entries
  # can't upgrade without upgrading Flutter itself.
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'term_glyph'
  - 'vector_math'
