name: json_conditional
description: A library to create conditional evaluators from JSON or JSON-like structures.
homepage: https://github.com/peiffer-innovations/json_conditional

version: 2.1.0+3

environment:
  sdk: ">=2.16.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  json_class: ^2.1.2+4
  meta: ^1.7.0

dev_dependencies:
  test: ^1.21.0
