name: json_conditional
description: A library to create conditional evaluators from JSON or JSON-like structures.
homepage: https://github.com/peiffer-innovations/json_conditional

version: 1.0.3+1

environment:
  sdk: ">=2.7.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  json_class: ^1.0.6
  meta: ^1.1.8

dev_dependencies:
  test: any
  test_coverage: any
