name: 'json_conditional'
description: 'A library to create conditional evaluators from JSON or JSON-like structures.'
homepage: 'https://github.com/peiffer-innovations/json_conditional'
version: '3.0.1+12'

environment:
  sdk: '>=3.0.0 <4.0.0'

analyzer:
  exclude:
    - 'lib/generated/**'

dependencies:
  json_class: '^3.0.0+13'
  meta: '^1.12.0'

dev_dependencies:
  flutter_lints: '^4.0.0'
  test: '^1.25.5'

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
