name: Dart Publisher

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub upgrade
    - name: Dart Analyzer
      run: dartanalyzer lib
    - name: Code Format
      run: dartfmt --set-exit-if-changed -w lib test
    - name: Run tests
      run: pub run test
    - name: Run test coverage
      run: pub run test_coverage
    - name: Publish
      uses: sakebook/actions-flutter-pub-publisher@v1.2.1
      with:
        credential: ${{ secrets.CREDENTIAL_JSON }}
        flutter_package: false
        skip_test: true
