name: Flutter Pull Request Checker

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: flutter packages get
    - name: Dart Analyzer
      run: dartanalyzer lib
    - name: Code Format
      run: dartfmt --set-exit-if-changed -w lib test
    - name: Run tests
      run: flutter test

